### ISSUE TITLE
Station incorrectly placed on map (Orléans)

### ISSUE THREAD

**Issue by bertrand-lupart** [n-b/Bicyclette#97]
At least one station in Orléans is incorrectly placed on the map (will check others).

Not sure how to correct this.

**Comment by n-b** [comment]
Hi Bertrand,

the app fetches data from the Orléans bikesharing webservices, including the stations location, so I’m afraid there’s not much I can do by myself. Which station is this exactly?

**Comment by n-b** [comment]
By the way: I realize you don’t really care about it, but this repo  doesn’t reflect the current state of the app, at all. For various reasons, I couldn’t publish the source anymore for some time. I need to reopen it ¯\_(ツ)_/¯

**Comment by bertrand-lupart** [comment]
Hello Nicolas,

I was thinking about "Place du Chatelet" because i didn't knew where it was located. But I just figured stations could just move on the map across application restart.

![chatelet_good](https://user-images.githubusercontent.com/2318559/30578135-a31ff180-9d12-11e7-833d-2cf1220e5b5c.PNG)
![chatelet_bad_1](https://user-images.githubusercontent.com/2318559/30578136-a34e334c-9d12-11e7-8624-e366b5f8d9b6.PNG)
![chatelet_bad_2](https://user-images.githubusercontent.com/2318559/30578137-a3525904-9d12-11e7-9457-82ae0854c8f7.PNG)

**Comment by bertrand-lupart** [comment]
Same with "Place de Gaulle"
![de_gaulle_good](https://user-images.githubusercontent.com/2318559/30578261-34a66828-9d13-11e7-9d6b-d10f84a5e960.PNG)
![de_gaulle_bad](https://user-images.githubusercontent.com/2318559/30578264-34cd69b4-9d13-11e7-8d2f-d9baf5a12831.PNG)

**Comment by bertrand-lupart** [comment]
Have to do some more tests, but it looks like latitude is almost right while longitude may be wrong.

As of the repo not being up to date, could you provide the URL you get the data from? Those provided in Cities.md seem outdated :
* https://www.agglo-veloplus.fr/component/data_1.xml
* https://www.agglo-veloplus.fr/getStatusBorne?idBorne={station_id}

Thank you,

**Comment by n-b** [comment]
Apparently, the current version of the app directly scraps the webpage at `https://www.agglo-veloplus.fr/fr/carte/`. I’ll try to find a better source.

**Comment by bertrand-lupart** [comment]
Orléans was totally broken some months ago. Thus, i went in touch with Cykleo which pointed me to https://admin.velossimo.com/services/terminal

Didn't had a look at it at the time, since in the meantime a fixed Bicyclette version showed up in the App store ;)

**Comment by bertrand-lupart** [comment]
After some more testing, i'm able to trigger the location problem zooming and moving the map. Zooming around and moving the map to the correct location can redraw the station back to the correct place, and eventually misplace another.

I'll manage to provide a screen recording.

Interestingly, when stations are misplaced, they're :
* misplaced at the same place(s)
* misplaced horizontally, vertical position seem always right

Looks more about a map drawing issue rather than wrong station locations from the source.

**Comment by bertrand-lupart** [comment]
Re-installed the app, and i can't trigger the problem anymore.

Will tell you if it strikes back.
