### ISSUE TITLE
Paris : Switch to Vélib' Métropole

### ISSUE THREAD

**Issue by bertrand-lupart** [n-b/Bicyclette#99]
Since switch from Vélib' (JC Decaux) to Vélib' Métropole (Smoovengo), application shows an error "Update failure"

**Comment by bertrand-lupart** [comment]
Stations aren't up to date anymore on Open Data Paris :
https://opendata.paris.fr/explore/dataset/stations-velib-disponibilites-en-temps-reel/

Couldn't find information about Smovengo web services, asked them on their contact form.

Guess data should be available, as displayed by this website:
http://bikes.oobrien.com/paris/

**Comment by n-b** [comment]
As a matter of fact, the “Vélib 2” dataset is available on another page: https://opendata.paris.fr/explore/dataset/velib-disponibilite-en-temps-reel/api/

¯\_(ツ)_/¯ 

This is what the upcoming release will be using, until a proper solution is found for electric bikes.
